// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCr_uMHrz1-utrnMRtKtiKtbt1uFvxbDk',
    appId: '1:119947985964:web:2558362db455c87a837d89',
    messagingSenderId: '119947985964',
    projectId: 'chatapp-myapp-new',
    authDomain: 'chatapp-myapp-new.firebaseapp.com',
    storageBucket: 'chatapp-myapp-new.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtpz3KqF97XJ24x7BKTQnNNrvGu85ukxo',
    appId: '1:119947985964:android:a301aace1a86fab7837d89',
    messagingSenderId: '119947985964',
    projectId: 'chatapp-myapp-new',
    storageBucket: 'chatapp-myapp-new.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCr_uMHrz1-utrnMRtKtiKtbt1uFvxbDk',
    appId: '1:119947985964:web:102da7cb89828e15837d89',
    messagingSenderId: '119947985964',
    projectId: 'chatapp-myapp-new',
    authDomain: 'chatapp-myapp-new.firebaseapp.com',
    storageBucket: 'chatapp-myapp-new.appspot.com',
  );
}
